### ISSUE TITLE
This version of the rendering library is more recent than your version of ADT plug-in

### ISSUE THREAD

**Issue by olegazyx** [khaledev/ADT#1]
ADT version: 24.2.0-20160319
SDK version: 25.1.3
SDK Platform 23 rev2

on ADT 23.0.7 everything OK

**Comment by khaledev** [comment]
Hello,
Choose the Android Lollipop (API 22) or less by clicking on the corresponding icon on top of the Graphical Layout to get ride of this error message.
A new patch will be released hopefully in the next week.
